apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html
  namespace: starwind-b
data:
  index.html: |
    <html>
      <head>
        <title>Starwind</title>
      </head>
      <body>Hello Starwind from Team B baby</body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: starwind-b
  namespace: starwind-b
spec:
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: starwind-b