kind: Deployment
apiVersion: apps/v1
metadata:
  name: starwind-b
  labels:
    app: starwind-b
  namespace: starwind-b
spec:
  selector:
    matchLabels:
      app: starwind-b
  template:
    metadata:
      labels:
        app: starwind-b
    spec:
      containers:
      - name: starwind-b
        image: nginx
        ports:
        - containerPort: 80
        resources:  
            limits:  
              cpu: 100m  
              memory: 10Mi  
            requests:  
              cpu: 100m  
              memory: 10Mi  
        volumeMounts:  
          - mountPath: /usr/share/nginx/html
            name: html  
      volumes:  
        - name: html
          configMap:
            name: nginx-index-html