apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html
  namespace: starwind-a
data:
  index.html: |
    <html>
      <head>
        <title>Starwind</title>
      </head>
      <body>Hello Starwind from Team A <br /> Does it work if I add this?</body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: starwind-a
  namespace: starwind-a
spec:
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: starwind-a