apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: starwind-a

commonLabels:
  app: starwind-a

resources:
- ../cluster-apps/arc-k8s-demo.yaml
- ../team-a/endpoints.yaml
 
patchesStrategicMerge:
 - ./replicapatch.yaml
