apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: starwind-a

commonLabels:
  app: starwind-a

resources:
 - https://github.com/AkshayGit07/Starwind-AKS-Arc-Gitops/blob/ec951b46243751ccd3de165cc148cf92d0f4883a/cluster-apps/arc-k8s-demo.yaml
 - https://github.com/AkshayGit07/Starwind-AKS-Arc-Gitops/blob/ec951b46243751ccd3de165cc148cf92d0f4883a/namespaces/team-a.yaml
 - https://github.com/AkshayGit07/Starwind-AKS-Arc-Gitops/blob/ec951b46243751ccd3de165cc148cf92d0f4883a/team-a/endpoints.yaml
 
patchesStrategicMerge:
 - replicapatch.yaml
